config/routes.rb
PocketSearch::Application.routes.draw do
  get "index/index"
  get "index/callback"
  get "index/sync"
  get "index/timeline"
  get "login" => "index#login"
  get "logout" => "index#logout"

  resources :links do
    collection do
      get 'crawl'
      post 'search'
    end
  end

  resources :users do
    collection do
      get 'unfollow'
      get 'follow'
    end
  end

  resources :items do
    collection do
      get 'main'
    end
  end

   root :to => 'index#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :user_id, :link_id, :created_at, :updated_at
  belongs_to :link
  belongs_to :user
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :content, :id, :status, :title, :content_type, :url, :uid
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :id, :pocket_access_token, :username
  has_many :items
  has_and_belongs_to_many :follows, :join_table => "users_follows", :class_name => "User",
  												:association_foreign_key => "follow_id"
  has_and_belongs_to_many :fans, :join_table => "users_follows", :class_name => "User",
  												:association_foreign_key => "user_id", :foreign_key => "follow_id"

  def sync
    parsed_url = URI.parse("https://getpocket.com")
    http = Net::HTTP.new(parsed_url.host, parsed_url.port)
    http.use_ssl = true
    res = http.get("/v3/get?state=all&consumer_key=11572-e9f22c44fc2b2cf25f14a560&access_token=#{pocket_access_token}")
    body = JSON.parse(res.body)

    body["list"].each do |k, v|
      pocket_id = v["item_id"]
      url = v["given_url"]
      title = v["given_title"]
      time_added = v["time_added"]
      content_type = get_content_type(url)

      link = Link.where("url = '#{url}'").first
      if link.blank?
        link = Link.create(:url => url, :title => title, :content_type => content_type)
      end

      has_link = false
     	self.items.each do |x|
        if x.link_id == link.id
          has_link = true
        end
      end
      unless has_link
        Item.create(:user_id => self.id, :link_id => link.id, :created_at => Time.at(time_added.to_i))
      end
    end
  end

  	def get_content_type(url)
		if url.match('^.+://[^/]+/?$')
			return "site"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery


end

app/controllers/index_controller.rb
require 'net/http'
require 'json'

class IndexController < ApplicationController

  def index
    if session[:uid]
      @user = User.find(session[:uid])

      @items = Hash.new
      last_date = ""
      @user.items.sort! do |x, y|
        y.created_at <=> x.created_at
      end
      @user.items.each do |x|
        cur_date = x.created_at.to_s[0,10]
        unless last_date == cur_date
          last_date = cur_date 
          @items[cur_date] = Array.new
        end
        @items[cur_date] << x
      end
      render :index
    else
      render :login, :layout => false
    end
  end

  def login
    redirect_uri = "http://localhost:3000/index/callback"

    parsed_url = URI.parse("https://getpocket.com")
    http = Net::HTTP.new(parsed_url.host, parsed_url.port)
    http.use_ssl = true
    res = http.post("/v3/oauth/request","consumer_key=11572-e9f22c44fc2b2cf25f14a560&redirect_uri=#{redirect_uri}")
    request_token = res.body[5,res.body.size]
    cookies[:request_token] = request_token
    redirect_to "https://getpocket.com/auth/authorize?request_token=#{request_token}&redirect_uri=#{redirect_uri}"
  end

  def logout
    session[:uid] = nil

    redirect_to :action=>"index"
  end

  def get_access_token
    p "="*50
    p "get_access_token"
    parsed_url = URI.parse("https://getpocket.com")
    http = Net::HTTP.new(parsed_url.host, parsed_url.port)
    http.use_ssl = true
    request_token = cookies[:request_token]
    p Time.now.to_f
    res = http.post("/v3/oauth/authorize","consumer_key=11572-e9f22c44fc2b2cf25f14a560&code=#{request_token}")
    p Time.now.to_f
    s = res.body.match('access_token=(.*)&username=(.*)')
    p Time.now.to_f

    p "="*50
    p "get_access_token"

    [s[1], s[2]]
  end

  def callback
    access_token, username = get_access_token
    @user = User.where("pocket_access_token = '#{access_token}'").first
    if @user.blank?
      @user = User.create("pocket_access_token"=>access_token, "username"=>username)
    end
    session[:uid] = @user.id

    redirect_to :action=>"index"
  end


  def sync
    user = User.find(session[:uid])
    user.sync

    redirect_to root_path
  end



  def timeline
    @user = User.find(session[:uid])
    @follows = @user.follows

    @items = Item.select("link_id, count(link_id) as link_num")
                      .where("user_id in (?,?)", @user, @follows)
                      .group("link_id")
    @items.sort! do |x, y|
      y.link_num <=> x.link_num
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@user = User.find(session[:uid])
		@items = @user.items

		render :json => {:name => "bo",:title => "this is a title"}
	end

	def main
		
	end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
  end

  def show
    @link = Link.find(params[:id])
  end

  def search
    keys = params[:key].split
    sql = "left join items ON items.link_id = links.id where items.user_id=#{session[:uid]}"
    keys.each_with_index do |x, index|
      sql += " and (links.content like '%#{x}%' or links.title like '%#{x}%')"
    end
    p "="*80
    p sql
    @user = User.find(session[:uid])
    @links = Link.joins(sql)
    # @links = Link.where(sql)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.find(session[:uid])
  end

  def unfollow
    follow_id = params[:follow_id] 
    user = User.find(session[:uid])
    unless follow_id.blank?
      follow = User.find(follow_id)
      user.follows.delete(follow)
    end

    redirect_to users_path
  end

  def follow
    follow_id = params[:follow_id] 
    user = User.find(session[:uid])
    unless follow_id.blank?
      follow = User.find(follow_id)
      user.follows << follow
    end

    redirect_to users_path
  end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
# encoding=utf-8
module IndexHelper
	def has_follow(user, follow)
		if user.id == follow.id
			return false
		end
		user.follows.each do |x|
			if x.id == follow.id
				return true
			end
		end
		return false
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/index/callback.html.erb
<h1>Pocket</h1>
Hi,<%= @user.first.username %>

<ul>
<% @links.each do |link| %>
  <li>
  <a href="<%= link.url %>"><%= link.title %></a>
  </li>
<% end %>
</ul>

app/views/index/index.html.erb
<div class="row">
  <div class="span8 offset2">
    <!--Sidebar content-->

    <% @items.each do |k, v| %>
    <div class="row date"><%= k %></div>
    <% v.each do |x| %>
    <% link = x.link %>
    <div class="row item">
      <a href="<%= link.url %>" target="_blank" class="title span7" title="<%= link.title %>"><%= link.title %></a>
      <% if link.content_type == "site" %>
      <span class="span1 view_text">站点</span>
      <% else %>
      <a href="<%= link_path(link.id)%>" target="_blank" class="view_text span1">阅读</a>
      <% end %>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/index/login.html.erb
<a href="<%= login_path %>">登录</a>

app/views/index/timeline.html.erb
<div class="row tabs">
  <div class="span3 offset7">
	<a href="" class="button">Day</a>
  <a href="" class="button">Week</a>
  <a href="" class="button">Month</a>
  </div>
</div>

<div class="row">
  <div class="span9 offset1">
    <% @items.each do |item| %>
    <% link = Link.find(item.link_id) %>
    <div class="row item">
      <span class="span1"><%= item.link_num %></span>
      <a href="<%= link.url %>" target="_blank" class="title span6" title="<%= link.title %>"><%= link.title %></a>
      <% if link.content_type == "site" %>
      <%= link.content_type %>
      <% else %>
      <a href="<%= link_path(link.id)%>" target="_blank" class="view_text span1">阅读</a>
      <% end %>
      <% unless link.crawl_status == 200 %>
      <span class="status span1"><%= link.crawl_status %></span>
      <% end %>
    </div>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>PocketSearch</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
  <%= javascript_include_tag "underscore" %>
  <%= javascript_include_tag "backbone" %>
  <%= javascript_include_tag "json2" %>
  
	<%= csrf_meta_tags %>
</head>
<body>


<div class="navbar">
	<div class="row">

  
  	<%= unless(@user.blank?) then @user.username end %>
  	<a href="<%= logout_path %>">退出</a>
  <a href="<%= root_path %>">我的书签</a>
  <a href="<%= index_timeline_path %>">时间线</a>
  <a href="<%= users_path %>">用户</a>
  <a href="<%= index_sync_path %>">同步</a>
  <a href="<%= main_items_path %>">Items</a>
  

  <%= form_tag(search_links_path, :method=>"post") do %>
  <input type="text" name="key" placeholder="search"/>
  <% end %>
  </div>
</div>
	<div class="container">
		
		<%= yield %>
	</div>


</body>
</html>

app/views/links/index.html.erb
<h1>Pocket</h1>
<a href="links/crawl">Crawl</a>
<%= form_tag(search_links_path, :method=>"post") do %>
  <input type="text" name="key"/>
  <input type="submit" />
<% end %>
<ul>
<% @links.each do |link| %>
  <li style="width:400px">
  <a href="<%= link.url %>" target="_blank"><%= link.title %></a>|
  <a href="<%= link_path(link.id)%>" target="_blank"><%= link.content_type %></a>
  </li>
<% end %>
</ul>

app/views/links/search.html.erb
<div class="row item">
  <div class="span8 offset2">
  <% @links.each do |link| %>
    <a href="<%= link.url %>" class="span6"><%= link.title %></a>
    <a href="<%= link_path(link.id)%>" class="span1">文字</a>
  <% end %>
  </div>
</div>

app/views/links/show.html.erb
<div class="article">
	<h2><%= @link.title %></h2>
<%= raw @link.content %>
</div>

app/views/users/index.html.erb
<div class="row tabs">
  <div class="span8 offset2">
  <%= @user.username %>关注了<%= @user.follows.size %>位用户:
  </div>
</div>

<div class="row item">
  <div class="span8 offset2">
  <% @users.each do |user| %>  
  <% unless user.id == @user.id %>
  <div class="row">
  	<span class="span2"><%= user.username %></span>
  	<span class="span1">关注:<%= user.follows.size %></span>
  	<span class="span1">粉丝: <%= user.fans.size %></span>
  	<% if has_follow(@user, user) %>
  	<span class="span1"><%= link_to("取消关注", unfollow_users_path(:follow_id => user.id)) %></span>
  	<% else %>
  	<span class="span1"><%= link_to("关注", follow_users_path(:follow_id => user.id)) %></span>
  	<% end %>
  </div>
  <% end %>
  <% end %>
  </div>
</div>